### ISSUE TITLE
颜值

### ISSUE THREAD

**Issue by DaSea** [TevinLi/amWiki#1]
能不能给个漂亮点的界面!

**Comment by TevinLi** [comment]
Thanks，其实一开始想的先实用，界面就做得有些简单了，后面会在这方面进行一些改进

**Comment by DaSea** [comment]
恩, 我现在在用, 因为不是做前端的所以不太会改, 其他的都太麻烦, 又懒得配, 用atom看到了, 确实蛮方便的.
