### ISSUE TITLE
代码段在移动端页面中显示不佳

### ISSUE THREAD

**Issue by pianzide1117** [TevinLi/amWiki#10]
过长的代码段在移动端页面中会换行。使得代码混在在一起不利于阅读。
建议代码段在屏幕缩小时，保持左右滚动条。

**Comment by TevinLi** [comment]
嗯，当时为了pc端能一次看全，让代码换行了，移动端确实保留滚动条比较好

**Comment by TevinLi** [comment]
已经在 [v0.6.4](https://github.com/TevinLi/amWiki/releases/tag/v0.6.4) 版本中添加区分，移动端代码段不换行保留左右滚动条
