### ISSUE TITLE
无法启动本地静态web服务器

### ISSUE THREAD

**Issue by syjsxxjy** [TevinLi/amWiki#102]
第一次正常运行，一段时间之后用浏览器访问wiki页面失败，web服务也无法启动。
请问怎样手动启动，或者造成这样状况可能的原因？

**Comment by TevinLi** [comment]
请提供更多信息
比如你是Atom还是命令行？一段时间大概多久？期间是否有其他特别操作？访问失败是哪种失败？无法启动是指无法重启吧，重启步骤是怎么样的？如此等等，请详细一些

**Comment by syjsxxjy** [comment]
错误信息是：

Network Error (tcp_error)
--
A communication error occurred: "No route to host"

用的是atom，菜单里使用“在浏览器打开当前文档”，第一次会提示本地静态服务器没有启动，是否启动。选择是之后会弹出浏览器，然后正常显示页面。隔一段时间之后本地服务器挂了，按F12访问页面就是上面的错误。用atom再次启动本地服务器也失败。请问具体是哪些服务，是不是需要安装新的功能，是否可以手动启动？

**Comment by syjsxxjy** [comment]
![qq 20151211234753](https://user-images.githubusercontent.com/7524140/32264967-02c2b2dc-bf1c-11e7-88f8-862d4a619f5c.jpg)我解决了，把本地Ipv4地址换成127.0.0.1或者localhost就可以正常访问了。可能是因为校园网的问题，不能用局域网地址访问。谢谢。

**Comment by TevinLi** [comment]
好的，感谢回馈信息！

另外，将来还会在 config.json 上增加一项可以指定访问 ip 和端口的配置项

**Comment by syjsxxjy** [comment]
好的。
