### ISSUE TITLE
希望除了markdown文件，可以支持html文件

### ISSUE THREAD

**Issue by shenbinglife** [TevinLi/amWiki#117]
有的时候，markdown文件无法写出的内容，使用HTML做出来的单页展示更好，所以希望能同时支持HTML， 不知道有没有这个功能或计划？

**Comment by mikusjelly** [comment]
markdown无法写出的内容？举个例子。

个人不建议去支持html文件，另外，markdown本身也支持简单的html标签，如<br/>等等。

**Comment by shenbinglife** [comment]
因为，怎么说呢，我希望发布一个前端文档，因为由前端人员写的，中间有些js插件演示之类的。所以希望能支持html单页。

**Comment by mikusjelly** [comment]
library目录存放的是markdown，这是没有问题的；对于其他类型的文件，为建议当作外链或附件来看。举个例子，图片，你可以使用本地路径也可以使用外链的方式展示。

amWiki是依赖http服务的，既然有http服务，那么就支持html文件。所以，在当前目录新增任意一个html文件，如hello.html，访问的时候，`http://localhost/hello.html`就能访问。

最后，只需要在markdown里面引用一下即可。
