### ISSUE TITLE
全文搜索的文本框应该响应回车按钮事件

### ISSUE THREAD

**Issue by pianzide1117** [TevinLi/amWiki#12]
搜索框通常都要监听回车按钮事件，这样更加易用。

**Comment by TevinLi** [comment]
嗯嗯，是的

**Comment by TevinLi** [comment]
已经在 [v0.7.2](https://github.com/TevinLi/amWiki/releases/tag/v0.7.2) 中添加此便捷操作，tks

**Comment by pianzide1117** [comment]
excellent
