### ISSUE TITLE
请问：未来会不会支持sublime作为IDE？

### ISSUE THREAD

**Issue by deepbluecao** [TevinLi/amWiki#134]
首先非常感谢TevinLi创作的amWiki，基于Markdown的Wiki完美地平衡了创作效率与呈现效果之间的关系。由于Atom太卡顿，尤其是对配置不高的电脑特别不友好，因此，我想问您未来会不会考虑支持sublime作为IDE？

**Comment by mikusjelly** [comment]
...跟sublime有什么关系？你甚至不用atom也可以使用amwiki。

**Comment by deepbluecao** [comment]
@mikusjelly 你是说用Nodejs-Npm来格式化目录和启动服务？请问在Windows系统的命令行中怎么用npm怎么启动amwiki服务并在Chrome中显示啊？我是学英语的，对nodejs不是很熟悉。

**Comment by deepbluecao** [comment]
@mikusjelly 哦，我明白了，谢谢！在Windows的CMD中，进入文库文件夹的根目录，用“amwiki -b”命令就可以在Chrome中打开Wiki页面了，更多内容可以用"amwiki -h"查阅。所以只要用Sublime编辑MD文件，用"amwiki -u"就能在Chrome中更新Wiki页面了。
