### ISSUE TITLE
希望提供一个自定义url的方法

### ISSUE THREAD

**Issue by coloz** [TevinLi/amWiki#137]
感谢作者

**Comment by mikusjelly** [comment]
这是什么问题？无法理解。

**Comment by coloz** [comment]
@mikusjelly 当前url是菜单层级+文件名，不利于传播和SEO

**Comment by mikusjelly** [comment]
我本人是自用，没这个需求。——你自己需求强烈的话，可以考虑改改。

**Comment by davinma** [comment]
举个例子，在 `$navigation.md` 文件中：
```
#### [首页](?file=首页 "返回首页")

##### 产品简介
- [产品简介](?file=003-其他服务/11-产品简介 "产品简介")
- 界面展示](?file=003-其他服务/12-界面展示 "界面展示")
```
可以将 `?file=00x-xxxxx/xx-xxxxx` 中的 `xxxxx` 改成英文或者拼音方式的字符，这样比较方便传播。至于  SEO，个人觉得靠改 URL 中的菜单层级 + 文件名作用真心不大，关键还是文档内容。

BTW，以上例子中的 `xxxxx` 部分如果是 CJK 字符，把地址复制到某些浏览器地址栏上，可能不会对这些字符进行 URL encode 编码，从而导致打不开 URL 地址。当然，能自定义是最好了。
