### ISSUE TITLE
添加Katex支持公式没有效果！

### ISSUE THREAD

**Issue by lmspace** [TevinLi/amWiki#139]
我想在amWiki中添加Katex来支持公式。
我在本地新建了一个HTML文件，来测试Katex的效果，本地测试显示是正常。
当我在amWiki中引入Katex后，在md文件中编写公式，amWiki的显示没有效果。

**Comment by lmspace** [comment]
本地HTML文件：
![1](https://user-images.githubusercontent.com/9404343/42936338-5430adea-8b3b-11e8-9464-8f639b2a8422.png)

本地显示效果：
![2](https://user-images.githubusercontent.com/9404343/42936346-590ca1fc-8b3b-11e8-94d0-a2becb1947c6.png)

amWiki的index.html文件：
![3](https://user-images.githubusercontent.com/9404343/42936353-5cf492ac-8b3b-11e8-88d2-a6ffb1935665.png)

amWiki的md文件：
![4](https://user-images.githubusercontent.com/9404343/42936357-61443ccc-8b3b-11e8-8480-0e35d368abad.png)

amWiki显示效果：
![5](https://user-images.githubusercontent.com/9404343/42936360-657dde88-8b3b-11e8-86a2-a642f2fb80f4.png)

**Comment by lmspace** [comment]
lssuse好像没人看啊？
我自己解决了，说一下方法哈。没什么技术含量（我是做底层的，捂脸），纯属模仿amWiki代码结构。

首先引入katex的js与css，不用引入auto-render.js了（因为没用上）。

在amWiki.docs.js文件加入如下代码：
```js
/**
     * 解析 markdown 数学公式
     * @param {String} html
     * @returns {String}
     * @private
     */
    Docs.prototype._renderMath = function (html) {
        var mathHtml =  html.replace(/\$\$(.*?)\$\$/g, function (m, s1, index) {
            return '<div id="math' + index + '">\n'
            + '<script>katex.render(String.raw`' + s1 + '`, math' + index + ', {displayMode: true});</script>\n'
            + '</div>';
        });
        return mathHtml = mathHtml.replace(/\$(.*?)\$/g, function (m, s1, index) {
            return '<div id="math' + index + '">\n'
            + '<script>katex.render(String.raw`' + s1 + '`, math' + index + ');</script>\n'
            + '</div>';
        });
    };
```
接着在渲染文档那个函数下添加如下代码：
```js
//数学公式
html = this._renderMath(html);
```
然后就可以使用`$`和`$$`来写公式了，`$`是嵌入式公式，`$$`是单行公式。ps：不知道有没有bug，欢迎拍砖！
写公式代码：
![1](https://user-images.githubusercontent.com/9404343/43042070-defc9c6c-8d62-11e8-8242-20257c2be2a6.png)
显示效果：
![2](https://user-images.githubusercontent.com/9404343/43042071-e7176422-8d62-11e8-8c84-190622928e56.png)

**Comment by lmspace** [comment]
lssuse好像没人看啊？
我自己解决了，说一下方法哈。没什么技术含量（我是做底层的，捂脸），纯属模仿amWiki代码结构。

首先引入katex的js与css，不用引入auto-render.js了（因为没用上）。

在amWiki.docs.js文件加入如下代码：
```js
     /**
     * 解析 markdown 数学公式
     * @param {String} html
     * @returns {String}
     * @private
     */
    Docs.prototype._renderMath = function (html) {
        var mathHtml = html.replace(/\$\$(.*?)\$\$/g, function (m, s1, index) {
            return '<div id="math' + index + '">\n'
            + '<script>katex.render(String.raw`' + s1 + '`, math' + index + ', {displayMode: true});</script>\n'
            + '</div>';
        });
        return mathHtml = mathHtml.replace(/\$(.*?)\$/g, function (m, s1, index) {
            return '<div id="math' + index + '">\n'
            + '<script>katex.render(String.raw`' + s1 + '`, math' + index + ');</script>\n'
            + '</div>';
        });
    };
```
接着在**渲染文档**那个函数下添加如下代码：
```js
//数学公式
html = this._renderMath(html);
```
然后就可以使用`$`和`$$`来写公式了，`$`是嵌入式公式`$$`是单行公式。ps：不知道有没有bug，欢迎拍砖！
写公式代码：
![1](https://user-images.githubusercontent.com/9404343/43042111-224f1e30-8d64-11e8-8f9c-563f83cbadf0.png)
显示效果：
![2](https://user-images.githubusercontent.com/9404343/43042113-27899182-8d64-11e8-9255-f98e32ed2c9f.png)

**Comment by lmspace** [comment]
lssuse好像没人看啊？
我自己解决了，说一下方法哈。没什么技术含量（我是做底层的，捂脸），纯属模仿amWiki代码结构。

首先引入katex的js与css，不用引入auto-render.js了（因为没用上）。

在amWiki.docs.js文件加入如下代码：
```js
    /**
     * 解析 markdown 数学公式
     * @param {String} html
     * @returns {String}
     * @private
     */
    Docs.prototype._renderMath = function (html) {
        var mathHtml = html.replace(/\$\$(.*?)\$\$/g, function (m, s1, index) {
            return '<span id="math' + index + '">\n'
            + '<script>katex.render(String.raw`' + s1 + '`, math' + index + ', {displayMode: true});</script>\n'
            + '</span>';
        });
        return mathHtml = mathHtml.replace(/\$(.*?)\$/g, function (m, s1, index) {
            return '<span id="math' + index + '">\n'
            + '<script>katex.render(String.raw`' + s1 + '`, math' + index + ');</script>\n'
            + '</span>';
        });
    };
```
接着在**渲染文档**那个函数下添加如下代码：
```js
//数学公式
html = this._renderMath(html);
```
然后就可以使用`$`和`$$`来写公式了，`$`是嵌入式公式`$$`是单行公式。ps：不知道有没有bug，欢迎拍砖！

写公式代码：
![1](https://user-images.githubusercontent.com/9404343/43042144-ec16fdb4-8d64-11e8-8f75-2fa272fd88c0.png)
显示效果：
![2](https://user-images.githubusercontent.com/9404343/43042146-f25ab698-8d64-11e8-8c7e-c759356592d0.png)

**Comment by lmspace** [comment]
lssues好像没人看啊？
我自己解决了，说一下方法哈。没什么技术含量（我是做底层的，捂脸），纯属模仿amWiki代码结构。

首先引入katex的js与css，不用引入auto-render.js了（因为没用上）。

在amWiki.docs.js文件加入如下代码：
```js
    /**
     * 解析 markdown 数学公式
     * @param {String} html
     * @returns {String}
     * @private
     */
    Docs.prototype._renderMath = function (html) {
        var mathHtml = html.replace(/\$\$(.*?)\$\$/g, function (m, s1, index) {
            return '<span id="math' + index + '">\n'
            + '<script>katex.render(String.raw`' + s1 + '`, math' + index + ', {displayMode: true});</script>\n'
            + '</span>';
        });
        return mathHtml = mathHtml.replace(/\$(.*?)\$/g, function (m, s1, index) {
            return '<span id="math' + index + '">\n'
            + '<script>katex.render(String.raw`' + s1 + '`, math' + index + ');</script>\n'
            + '</span>';
        });
    };
```
接着在**渲染文档**那个函数下添加如下代码：
```js
//数学公式
html = this._renderMath(html);
```
然后就可以使用`$`和`$$`来写公式了，`$`是嵌入式公式`$$`是单行公式。ps：不知道有没有bug，欢迎拍砖！

公式代码：
![1](https://user-images.githubusercontent.com/9404343/43042240-01d44820-8d68-11e8-8cbb-606e46ad5291.png)
显示效果：
![2](https://user-images.githubusercontent.com/9404343/43042242-07f78ee2-8d68-11e8-9c18-b4b4bb7ce716.png)

**Comment by mikusjelly** [comment]
每个喜好不一样，个人喜好用Mathjax。
