### ISSUE TITLE
抽取页内目录，无法跳转

### ISSUE THREAD

**Issue by mikusjelly** [TevinLi/amWiki#15]
如果
```
## 1. Part1
```
抽取后，会变成
```
1. [1.1 Part1](#1.1Part1 "1.1 Part1")
```
使用`1.1Part1`则无法跳到Part1。

而：
```
1. [1.1 Part1](#1.1 Part1 "1.1 Part1")
```
才能跳到Part1。

**Comment by mikusjelly** [comment]
感觉直接解析 [TOC] 标签会更好，这样，就不需要手工去生成这个页内目录了。

**Comment by TevinLi** [comment]
[TOC] 标签是一个很好的实现目录的方式，当初是考虑到与 github 文档兼容问题而采用了的直接生成目录，后面打算这样支持：

- 可以 “直接生成目录” 
- 可以用 [TOC] 标签 指定的创建目录及创建的位置
- 在右侧“返回顶部”按钮上方较靠近的位置，新增一个悬浮栏位，鼠标悬浮或点击后显示目录
 (文档较长时比较有用)

这样，对任意文章就可以有三种目录方式提供选择，同时也便于和市面上各大平台兼容

**Comment by mikusjelly** [comment]
第三点很不错，期待更新。:smile:

**Comment by TevinLi** [comment]
已经于 [v0.7.4](https://github.com/TevinLi/amWiki/releases/tag/v0.7.4) 添加以上功能，目录现在可以有三种选择

**Comment by mikusjelly** [comment]
@TevinLi 0.7.5更新了，但是，貌似不支持TOC。
我直接将[TOC]放在文档的最前面，好像不行。
请问下，怎么用？

**Comment by TevinLi** [comment]
是不是没有更新你项目下的文件，在 Atom 中更新只是更新了插件哦，需要从 config.json 重新创新才会重新输出项目 web 端工作的 js、css 等资源

**Comment by mikusjelly** [comment]
确实，可以了。多谢。
