### ISSUE TITLE
请问如何解决"The requested URL xxx was not found on this server."的问题呢？

### ISSUE THREAD

**Issue by YaoXuanZhi** [TevinLi/amWiki#18]
amwiki作者你好，我遇到了一个麻烦，问题是这样的：
        我在平板电脑上将一个文库上传到bitbucket中，然后在另外一台机子上下载下来，使用Atom定位到这个文库的目录之后，当我点击“在浏览器打开当前文档”菜单后，浏览器就出现了“The requested URL xxx was not found on this server.”的页面，请问有没有解决方法解决这个问题呢。
![sp161202_092500](https://cloud.githubusercontent.com/assets/14124918/20819717/39b2712c-b871-11e6-846d-7bd0420e9d79.png)

**Comment by TevinLi** [comment]
你好，临时办法是，打开 config.json 重新创建文库 （这个操作不会更改已有library）  

这是当前版本文库记录方式不够清晰造成的，也是开发之初规划不够清晰遗留下来的一个典型问题，近期正在重新设计对文库记录的管理，将会比现在的版本更加强壮

**Comment by YaoXuanZhi** [comment]
好的，多谢作者大大的给力回答啦，我后来也摸索到了这个办法，总算可以在浏览器打开wiki浏览啦，期望你在后来的版本里修复这个问题啦(☆▽☆)。对啦，amwiki的确很好用，我目前将 一些零散的知识用它来整理了一下，感觉相当有条理啦，多谢大大将它发布出来啦~\(≧▽≦)/~
