### ISSUE TITLE
amwiki支持包含空白字符的文件路径么

### ISSUE THREAD

**Issue by YaoXuanZhi** [TevinLi/amWiki#19]
作者大大你好，我在使用amwiki编写文章的时候遇到了一个问题，情况是这样的：
因为amwiki是通过抽取Library目录下的文件结构来生成对应的页面导航的，所以.md的文件名自然就会影响到导航页面上的文字。现在我想在导航上面显示“XXXWindows SDK”等字样，里面包含了空白字符，按道理来说，此时我也应该为此对应的页面创建一个.md文件，文件名类似“001XXXWindows SDK”等等，创建文件成功后，我执行“在浏览器中打开此文档”的功能时，发现它会自动定位到amwiki的首页上，无法定位到当前.md文件对应的网页上，假设将这些空白字符用下划线等来代替之后，则是正常的。
情况大致如此了，其实我是想让导航页上的文本不带有下划线等阻碍阅读的字符，有没有办法解决呢，当然，不包括换名字啦〒▽〒

**Comment by TevinLi** [comment]
嗯，有时候文件名确实需要是有空格的 :smiley:   
这个问题只需要一个小改动，webServer.js 第197行加上 `.replace(/ /g, '%20')`  就可以容许带空格的文件名  
在下一个版本 0.7.6 中会带上这一修复

**Comment by YaoXuanZhi** [comment]
多谢大大的给力支持啦O(∩_∩)O~~

**Comment by TevinLi** [comment]
已经在 [v0.7.6](https://github.com/TevinLi/amWiki/releases/tag/v0.7.6) 版本中，修复此问题
