### ISSUE TITLE
点击手机端的目录之后后，没有任何跳转反应呢，这是肿么回事呢

### ISSUE THREAD

**Issue by YaoXuanZhi** [TevinLi/amWiki#22]
大大你好，又要麻烦你啦，今天我在手机端访问我的在线wiki时，发现点击了wiki自动生成的目录后，页面没有任何跳转的反应呢，倒是被点中的条目变成暗红色了。我这个是在红米的默认浏览器上发现这个问题的，其他手机还没有测试，不知为何导致的呢？

**Comment by TevinLi** [comment]
是 [TOC] 标签生成的目录还是？是说PC端可以移动端不行么，我好像没重现出你所说的问题

**Comment by YaoXuanZhi** [comment]
哦，我刚刚在朋友的UC浏览器上测试一下，的确没有发现这个问题；不过我的红米手机自带的浏览器上的确出现了这个问题。

**Comment by TevinLi** [comment]
那就奇怪了，目录链接都是页内锚点了，这个应该不会有兼容问题，除开这个就还有可能是目录生成问题，但是我也是用的很普通的正则语法呀，也应该不会有兼容问题，而如果js报错挂掉了，那页面应该不会完整创建出来就这里失效了...  
这个，你截个图出来看看

**Comment by YaoXuanZhi** [comment]
哦，这个是所有.md文件生成的共同目录，也就是amWiki左边的侧边栏啦，页内右下角那个小目录的功能是正常的。对啦，差点忘记了，能能修改一下右下角的小目录的响应消息呢
![image](https://cloud.githubusercontent.com/assets/14124918/21074412/56b116f2-bf33-11e6-8b91-7cd90b831306.png)
我觉得做比较符合用户的操作习惯，特别是手机用户。
目前手机访问github比较慢，我迟点再截个图啦

**Comment by YaoXuanZhi** [comment]
![image](https://cloud.githubusercontent.com/assets/14124918/21074659/a66632bc-bf39-11e6-8d30-4b4871c8aed9.png)
上面是UC浏览器上的截图啦，我在手机端遇到的问题都已在上面说明啦，希望大大可以看明白啦><，另外，关于手机端的目录样式，个人有点小建议哦，其实Github官方的目录样式还是蛮不错滴。

**Comment by TevinLi** [comment]
移动端点击其他位置收回页内目录，这个可以有  

移动端的文库导航的显示问题，略微能看到下面一层其实是我有意的，目前版本可以再降低一点透明度来提高些可阅读性  
不透明白底这种，嗯，我也想到了解决办法，视觉上确实是要好一些，不过慢慢来吧，这个问题我先记下来

**Comment by YaoXuanZhi** [comment]
好的，麻烦大大啦

**Comment by TevinLi** [comment]
已经在 [v0.7.6](https://github.com/TevinLi/amWiki/releases/tag/v0.7.6) 版本中，修复移动端页内目录折叠问题

**Comment by TevinLi** [comment]
文库导航的问题，我还是没重现出来  
如果说是旧手机不兼容的话，也就是手工操作 history 的 api 在低版本浏览器上不支持，但是我有做兼容处理了，低版本浏览器上点击文库导航，是一个会刷新页面的跳转操作，而不是正常这样只读取和替换内容  
其他的 api 除非是古董级安卓，否则都应该是支持的，而红米肯定有安卓 4.x 以上，不是古董机，没有实体机呀，看不到问题...

**Comment by YaoXuanZhi** [comment]
哦，这样也就没办法了，大大先把这个问题搁置吧。近段时间我也打算重温一下js，看看能不能找到问题><，毕竟实体机在我手上呢……
