### ISSUE TITLE
能不能在“导出到Github Wiki”的时候，也处理一下Html代码块里的图片路径呢

### ISSUE THREAD

**Issue by YaoXuanZhi** [TevinLi/amWiki#23]
大大，这样的，之前在另外一个issue的时候，就提到了这个问题了，目前你是通过下面这种方式来识别图片地址并转换的
![image](https://cloud.githubusercontent.com/assets/14124918/21101105/8c6c20f4-c0b2-11e6-94d5-5eaf2b020733.png)
但是，此时，在处理这种html代码块的图片链接上失效了，能否也能让其支持这种图片地址呢？
![image](https://cloud.githubusercontent.com/assets/14124918/21085690/bebeb5ca-c04f-11e6-9e46-e5ada63835e1.png)
类似的图片链接还有href等等。

**Comment by TevinLi** [comment]
src 已经加了，不过，href 也有呀？是要下载还是？  
嗯，加下也好，只有 a 标签的 href 吧

**Comment by YaoXuanZhi** [comment]
嗯嗯，麻烦啦

**Comment by TevinLi** [comment]
嗯嗯，这些扩展资源作为补充，应该被支持
已经 commit 啦，下一版本发布就会带上 :tea:

**Comment by TevinLi** [comment]
已经在 [v0.7.7](https://github.com/TevinLi/amWiki/releases/tag/v0.7.7) 版本中，添加 html img 和 a 、markdown 链接的相对 assets 地址导出转换
