### ISSUE TITLE
能否让amWiki支持忽略大小写的搜索呢

### ISSUE THREAD

**Issue by YaoXuanZhi** [TevinLi/amWiki#24]
大大你好，这次我是提一个建议的，目前amWiki已经支持目录筛选和全文搜索啦，但是我发现它不支持忽略大小写的搜索功能呢，其实我觉得忽略大小写应该比较贴合实际的，毕竟很难说，有谁可以完全记住要搜索的关键字的大小写的，另外能否支持模糊搜索呢，或者高级些的正则表达式搜索等功能，我觉得这块功能也是可以强化一下滴。(o゜▽゜)o☆
![image](https://cloud.githubusercontent.com/assets/14124918/21213501/b6e3b648-c2cf-11e6-91a6-920530d9a667.png)

**Comment by TevinLi** [comment]
哈哈，这个倒是正合我意，尤其你说支持正则，让我眼前一亮  
其实这一块按照我的计划，是一个很深的板块，也就是说模糊搜索这个了，它的实现条件其实是蛮高的，因为要分词，不分词计算量太恐怖，而分词也不是一个简单事情，尤其分词环境不是在服务器端  
也是由于设计得有点大了，所以优先级没安排那么高，现在安排先做其他的东西了  
各种需求其实还有很多呀，我笔记上都列了一个列队了，这些功能我也记下啦，慢慢来 :blush:

**Comment by YaoXuanZhi** [comment]
好的，期待ing

**Comment by TevinLi** [comment]
大小写忽略可以先做，这个倒是不复杂

**Comment by TevinLi** [comment]
已经在 [v0.7.7](https://github.com/TevinLi/amWiki/releases/tag/v0.7.7) 版本种，添加搜索的大小写忽略
