### ISSUE TITLE
全文搜索功能在当前页面内容不多时应当自动扩展页面高度

### ISSUE THREAD

**Issue by pianzide1117** [TevinLi/amWiki#26]
全文搜索功能，现在采用的是当前面上类似弹层的做法实现的。
这样就受到了当前页面大小的约束，当前页面特别大时也特别大，特别小时也特别小。

应当采用和当前屏幕高度相适应的高度或固定高度作为搜索结果的显示高度。

同时，若有必要的话，需要浮动搜索栏。

**Comment by TevinLi** [comment]
嗯，是的，现在 Web 端页面的体验其实是有不少问题的  
其实页面布局我是打算换成左右两个区域独立滚动那种，这样就没有高度问题了，而且还有两外的两个问题也能在这种情况下改善
