### ISSUE TITLE
Mac OS  10.12.2 (16C67) F12失效

### ISSUE THREAD

**Issue by jimmywzm** [TevinLi/amWiki#27]
Mac OS 10.12.2 (16C67) 安装 amWiki 后，出现：

1. 键盘点击F12没有任何效果。
2. 鼠标点击 amWiki 轻文库 > 在浏览器打开当前文档也没有任何效果。:sob:

请问如何解决？

**Comment by TevinLi** [comment]
还是有这个问题？囧...  
看来只能改下判断方式了，等下一个版本发布再看看  
（临时办法麻烦点，可以自己搭个服务器访问）

**Comment by TevinLi** [comment]
已经在 [v0.8.0](https://github.com/TevinLi/amWiki/releases/tag/v0.8.0) 中，再次尝试修复 Mac 的 F12，看看问题是否有解决

**Comment by jimmywzm** [comment]
恩~刚测试过了，终于没有问题了~感谢！
