### ISSUE TITLE
为何amWiki不支持任意级别的文库目录索引呢

### ISSUE THREAD

**Issue by YaoXuanZhi** [TevinLi/amWiki#28]
大大又麻烦啦，我这段时间着手将amWiki移植到VS Code之中，在搞粘贴图片模块的时候，发现你在这里仅仅考虑三级以内的文库目录，不过我在移植的时候，已实现了任意深度级别的粘贴截图功能，但是在静态服务器上访问的时候，发现不能解析三级目录以上的.md文件，后来发现，这个是因为makeNav.js文件中已仅仅是实现了三级以内的目录结构的解析，所以出现了这个问题。因此，我这里有一个疑问，为何不可以实现N级文库目录呢？能说说原因吗？

**Comment by TevinLi** [comment]
在着手移植到VS Code？这个不错！我也在考虑，不过只是想了想，毕竟精力有限呀，做不来那么快  
  
包括这个无限级目录支持也是，这功能是有计划做的，只是因为麻烦些，优先级没那么高，下一步打算是 Atom 工作端重构，再然后才是无限级目录

**Comment by YaoXuanZhi** [comment]
嗯嗯，明白了，主要是我发现directories.js和pasterImg.js里面的代码只是实现了三级目录，所以有点懵逼了，现在我已经在粘贴截图的功能上支持了无限级目录，不过directories.js的目录解析中还没有调整到无限级目录，我私以为是因为这样做会引起什么奇奇怪怪的问题，所以有此一问啦。目前移植工作已经完成了8成左右吧，还差自动化模块和拖曳图片模块的功能没有移植，所以，目前在VS Code中已经可以正常使用amWiki了，但是某些高级功能还没整合><
这个是我移植amWiki的项目：https://github.com/YaoXuanZhi/amWikiForVSCode，
有空帮忙指正下啦><

**Comment by YaoXuanZhi** [comment]
哦，对啦，我移植成功后，打算将amWiki以amWIkiForVSCode发布到https://marketplace.visualstudio.com上，可以么><

**Comment by TevinLi** [comment]
额，这个问题我还不知道怎么回答你，VSCode的情况我还没有考察，我不确定我自己会不会整这个移植以及假设去整的话怎么整  
其实，正常来说，我应该提前占坑的，实在是整考试的事情耽误了我太多的进度

**Comment by YaoXuanZhi** [comment]
嗯嗯，确实应该如此，这样吧，我将我这边移植的amWiki项目提交给你，然后你另外开一个目录来合并即可。

**Comment by TevinLi** [comment]
好呀好呀，如果VSCode确实好用，那移植肯定是有必要的，不过可能会等些天才能处理，还有几天我就考试了，这考试我准备半年了

**Comment by TevinLi** [comment]
看到啦，感谢支持哈  
这项目是我想做的事情，不会让你失望的，嘿嘿

**Comment by TevinLi** [comment]
可以加你联系方式么？:sweat_smile:

**Comment by TevinLi** [comment]
@YaoXuanZhi  你的VSCode移植版本由你发布到vs的应用市场上吧，由于精力有限，vs我自己打算不兼顾开发啦

**Comment by YaoXuanZhi** [comment]
哦，这样啊，好的，我看看可不可以解决无限级侧边栏目录的切换问题，然后再发布吧，目前感觉还是有些Bug呢(⊙o⊙)…
