### ISSUE TITLE
建议将文本的目录格式标号改成Word那种

### ISSUE THREAD

**Issue by RockerHan** [TevinLi/amWiki#33]
如:
1 标题1
1.1 标题1.1
2 标题2
2.1 标题2.1
2.2 标题2.2

可参考demo：http://baike.baidu.com/item/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/192

**Comment by mikusjelly** [comment]
关于目录格式，为觉得还是自己手工写比较好。我现在发现的情况是，如果为自己手工写标题的话，会变成：
```
1. 1. AAA   
     i. 1.1 BBB
     ii. 1.2 CCC

或者
1. 第一章 AAA   
     i.  第一节 BBB
     ii. 第二节 CCC
```

看起来不好看 -，-。

**Comment by TevinLi** [comment]
到时候加一个检测吧，如果手工写过序号，不再重复

**Comment by mikusjelly** [comment]
今天更新到了1.2.1，发现一个奇怪的问题。
用atom启动本地服务的话，不会添加序号；
如果使用 `python -m http.server ` 的话，还会添加序号，只能把添加序号的那段代码删掉才行。
（平时查阅wiki的话，这样启动比较方便）

**Comment by mikusjelly** [comment]
已解决 —— 浏览器的缓存问题。

**Comment by TevinLi** [comment]
好的，其实刚刚也在怀疑这个
