### ISSUE TITLE
Amwiki同步到Web端

### ISSUE THREAD

**Issue by Mistry-lee** [TevinLi/amWiki#34]
Amwiki生成的文件有没有办法自动同步到Web端,我现在理解的就是写好后手动上传到Web端.因为手上有一个VPS,自己做了虚拟空间.想知道除了github还有其他办法吗?

**Comment by TevinLi** [comment]
同步代码的办法有很多吧，ftp、git、hg 等众多软件，甚至可以直接在 atom 中安装 ftp、git 插件来同步，他们都已经做得很好了，amWiki 不打算涉及这一块

**Comment by yangshare** [comment]
atom 中安装 ftp，因为文档又中文，乱码，这怎么解决哇

**Comment by TevinLi** [comment]
gbk 和 utf8 的问题，但这是 ftp 本身要解决的问题吧，ftp 服务器和 ftp 软件设置配合应该就能解决了  
比如说，有些 ftp 服务器有“对所有已收发的路径和文件名使用UTF－8编码”的选项，而有些 ftp 传输软件则有“如果服务器支持就使用 utf8，否则使用本地编码”的选项

**Comment by yangshare** [comment]
首先谢谢你的回复，我用的阿里云Linux主机做的wiki服务器，而atom那些大神写的ftp插件编码没看到有设置，我尝试过很多ftp插件，从远端拉下来都是乱码，这个问题暂时的解决不了。我只有写好文档，然后用xftp软件同步一次

**Comment by TevinLi** [comment]
嗯，从 linux 系统上拉下来的文件文件名是 utf8 编码的，windows 并不认识，如果插件没有编码设置，确实不怎么好解决，暂时还是先用专门的 ftp 软件吧  
一定要说方法的话，倒是有一个思路，可以整一个菜单功能，将 library 下所有文件名批量转 gbk，这样 windows 就认识了，但这个解决方法貌似也不够优雅，因为这需要服务器接受 gbk 文件名时，能转为 ut8，否则服务器上的会乱码
