### ISSUE TITLE
请问AMWiki生成的网页能否做RSS订阅源

### ISSUE THREAD

**Issue by Mistry-lee** [TevinLi/amWiki#36]
**请问AMWiki生成的网页能否做RSS订阅源,该怎么做呢**

**Comment by TevinLi** [comment]
目前不支持RSS，按现在已有的规划可能没有开发计划  
主要问题是，由于项目定位为不做数据库全部都是静态文件，所以记录文档创建时间或修改时间的是文件属性，而这个属性是很容易失真的  
如果撸一套记录算法，这个规模可能会比较大，因为文件名也可以改的，改文件名的时候可能程序并不知道  
除非能解决这个问题，否则开发RSS意义不大
