### ISSUE TITLE
希望支持footnote（脚注）

### ISSUE THREAD

**Issue by mikusjelly** [TevinLi/amWiki#37]
Hi @TevinLi ，

有时候，需要引用一些其他网站、文章的内容，需要用到脚注，希望能支持。

**Comment by TevinLi** [comment]
好的，收到

**Comment by TevinLi** [comment]
footnote 脚注已添加，有部分规则可能和其他平台略有区别

- 如果只有底部脚注正文而文章中没有引用，此条脚注将被隐藏
- 如果只有文中引用没有底部脚注正文，一条新的脚注将添加到脚注列表末尾，且以引用标记的标记名称为正文
- 引用标记名称，支持数字字母和空格
- 脚注正文支持 titile 属性，但 title 加在引用标记上

**Comment by mikusjelly** [comment]
多谢。
