### ISSUE TITLE
关于Ctrl-D快捷键

### ISSUE THREAD

**Issue by mikusjelly** [TevinLi/amWiki#38]
今天写代码的时候，发现被amWiki占用了。

因为ctrl-d经常会用到，所以我把amWiki\keymaps\keymaps.cson中的这一行注掉了。
```
# "ctrl-d": "amWiki:catalogue"
```

个人不大推荐使用`ctrl-d`，而且提取h2、h3标题为页内目录很少用，因为用了TOC。

**Comment by TevinLi** [comment]
嗯嗯，提取目录不是一个高频操作，设置快捷键确实意义不大，我释放出来吧
