### ISSUE TITLE
Ubuntu 上 atom 没有$navigation.md 文件

### ISSUE THREAD

**Issue by githubzhaoqian** [TevinLi/amwiki#4]
支持一下 很实用的一个 插件 666665+1

**Comment by TevinLi** [comment]
收到，我装个虚拟机试下看看

**Comment by githubzhaoqian** [comment]
大神辛苦啦

**Comment by TevinLi** [comment]
大神就算不上啦，主要是没Ubuntu的机子，只好用虚拟机了...

**Comment by TevinLi** [comment]
不过可能要略微等一些时间了，我对现在采用文件监听来工作的方式不是很满意，因为我发现监听二级目录后一级目录居然被锁定不能改名了
看了一下atom的treeView实现方式，发现是操作监听而不是文件监听的，我打算也改成这样

**Comment by githubzhaoqian** [comment]
理解，waiting……

**Comment by TevinLi** [comment]
是不是虚拟机和真机有些不一样，我用VirtualBox装UbuntuKylin16，进去有看到$navigation.md文件的哦，不过倒是有其他的报错

**Comment by githubzhaoqian** [comment]
那可能是我装wine 的问题么？  感觉安装了这东西  系统总是有些怪怪的  随后我卸载了试试

**Comment by githubzhaoqian** [comment]
可能是我用root身份安装的插件的问题 我卸载重新安装 可以了   谢谢

**Comment by TevinLi** [comment]
客气啦，能在产品初期参与体验并提出问题，我也很是感谢 :smiley:
