### ISSUE TITLE
移动端导航自动收起

### ISSUE THREAD

**Issue by cainding** [TevinLi/amWiki#40]
hi,大神,正在使用你的amWIKI在做文档,发现在移动端浏览的时候,点击具体的导航项后,虽然页面有跳转但是因为导航菜单没有自动收起,导致不知道页面有没有跳转,必须手动点击那个X的图标才能关掉遮盖全屏的导航菜单,才能发现实际上页面已经跳转到目标页.
能否加上移动端点击了导航中具体的页面,在页面发生跳转时,自动关闭导航菜单???

**Comment by TevinLi** [comment]
好的，收到

**Comment by Mistry-lee** [comment]
大大,刚刚更新了版本,发现手机端浏览已经可以自动关闭导航栏,可是为什么点搜索的时候不自动关闭导航栏呢!!!

**Comment by TevinLi** [comment]
囧...，有道理，下一版我就加上，Thanks！
