### ISSUE TITLE
ctrl + shift +v 与 markdown-img-paste的功能相冲突

### ISSUE THREAD

**Issue by tanboyu** [TevinLi/amWiki#41]
如果开启使用amwiki后，在非amwiki文档编辑（编辑md文档）时，利用markdown-img-paste的功能快速黏贴图片的功能就会提示报错。
提示 需要在library下打开md文档编辑，才能使用快捷图片黏贴功能。

**Comment by TevinLi** [comment]
嗯，这个问题倒是没考虑周到，我看看怎么释放给到下一个插件

**Comment by TevinLi** [comment]
研究了一下，因为 Atom 的机制，同一个地方同一种按键组合只能触发一种类型的事情，否则就会存在多个插件一起进行多种操作的混乱
所以这个快捷冲突可能没法从插件本身上来解决了，可以从 菜单 -> File -> Settings -> Packages -> amWiki(点进去) -> Keybindings 把 Enable 取消，释放快捷键绑定

不过快捷键虽然释放绑定了，但是功能还在，下一版本将在 菜单 -> amWiki轻文库 中添加一栏“从剪切板粘贴截图”，这样在释放了快捷键后功能还可以继续使用的

**Comment by TevinLi** [comment]
发现 Atom 目前有个 Bug，这个插件 Keybindings 的 Enable 取消后，下回不能直接到 Keybindings 这一栏了(这一栏还在，只是被隐藏了)，没法再把 Enable 重新选上，很是麻烦  
我已经把这个问题在 Atom 的 Github 中发 issue 了：https://github.com/atom/atom/issues/14319

PS：现在条件下强行重新显示消失的 Keybindings 栏也是有办法的，`Ctrl+Shift+i` 能唤出一个调试面板，如果您会用，那应该很简单就能让它重新显示出来，如果您不会用，那估计都能写一篇小教程了
