### ISSUE TITLE
图片显示大图的问题

### ISSUE THREAD

**Issue by Mistry-lee** [TevinLi/amWiki#44]
有一个问题想问一下,文库中的图片是使用的七牛的图片链接,是否能够实现点击图片变大呢!
因为我不知道是文库的问题还是七牛图片的问题,如果不是amwiki的问题也请告诉我一下,谢谢大大!

**Comment by TevinLi** [comment]
不是七牛的问题，是web端还没有写图片查看程序，写了就可以点击放大啦，这个我记下后面某个版本我加上来

**Comment by Mistry-lee** [comment]
@TevinLi 原来如此,那我就稍微等等吧!

**Comment by TevinLi** [comment]
已经在 [最新预览版](https://github.com/TevinLi/amWiki/archive/preview.zip)  中添加大图显示的问题，如需正式版，请耐心等待 v1.1.3 发布
