### ISSUE TITLE
图片自定义大小问题

### ISSUE THREAD

**Issue by lithromantic** [TevinLi/amWiki#45]
图片目前不支持自定义大小吗？

**Comment by TevinLi** [comment]
可以加入支持  
其实这个扩充语法很早就在考虑中啦，不过一直没有纳入排期，既然提出有需要，那近期我就加进来吧

**Comment by TevinLi** [comment]
已经能下载到包含自定义图片大小解析的 [预览版](https://github.com/TevinLi/amWiki/archive/preview.zip) 了，如需正式版，请耐心等待 v1.1.3 发布

**Comment by TevinLi** [comment]
自定义图片大小和对齐方式的语法：

> **`![](...=300-300-r)`**

其中 **=300-300-r** 是设置图片的，可以写成：
- **`=300×300`** 设置宽高
- **`=300-300`** 同上
- **`=300-`** 只设宽
- **`=-300`** 只设高
- **`=--l`** (不设大小)嵌入占位形式的左对齐
- **`=--r`** (不设大小)嵌入占位形式的右对齐
- **`=--c`** (不设大小)独占一行形式的居中对齐

例如：  
`![alt text](assets/003/001-01a02027.png=300-150-r "title text")`  
解析成：  
`<img src="assets/003/001-01a02027.png" widht="300" height="150" align="right" alt="alt text" titile="title text">`
显示效果：

| ![](https://user-images.githubusercontent.com/11657489/27000336-ca6adeb0-4de1-11e7-96ac-7fda4b36cd85.png) |
| --- |

**Comment by mikusjelly** [comment]
可以考虑更新到 wiki里面去了……（来这里搜了2次 ）
https://github.com/TevinLi/amWiki/wiki/Markdown%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B#%E5%9B%BE%E7%89%87

**Comment by TevinLi** [comment]
嗯嗯，其实在 amwiki.org/doc 上有规划了，不过还没写到这一部分来
