### ISSUE TITLE
能否支持多級目錄？

### ISSUE THREAD

**Issue by Quantizen** [TevinLi/amWiki#5]
謝謝你的貢獻！

看文檔中的說明，好像只支持二級目錄。

再者，markdown 轉換爲 html 這一步用的是什麼呢？ 還是說直接在 github 上託管的 markdown 文件？能否本地用 Pandoc 轉換成 html 文件，然後託管到 github 呢？

**Comment by TevinLi** [comment]
多级目录这问题我也思考过，主要是web端展示时导航栏不好显示，如果有好的建议，欢迎提供 :smiley:  
markdown转html这一步是在web端浏览器上实现的，ajax读取`.md`文件后由js解析成html，不需要其他软件支持

**Comment by Quantizen** [comment]
多級目錄可以參考[gitit](https://github.com/jgm/gitit)的文件夾形式的展示。

markdown轉html在web端實現，對於數學公式顯示好像沒有太好的解決方案。比如`_`在數學公式中是腳標的意思，但在markdown中是斜體的意思，兩者有時會衝突。

**Comment by TevinLi** [comment]
在后续某版本中将会加入无限级子目录支持，敬请期待，感谢建议！  
由于觉得数学公式使用场景不多，amWiki暂时没有加入数学公式支持，如果加入，也应该会考虑使用 \`\`\` \`\`\` 标记的代码块来实现，不会采用行内模式，所以不会有冲突的问题

**Comment by mikusjelly** [comment]
这个多级目录感觉还是有必要的。无限倒未必，我发现还是用到3级的。期待更新。

**Comment by TevinLi** [comment]
嗯嗯，多级目录肯定有滴，不止3级

**Comment by mikusjelly** [comment]
Hi @TevinLi
更新到1.0.6了，应该还没支持3级目录吧（我这测试不成功）。
看commit描述，不是很确定是否已经实现该功能。

**Comment by TevinLi** [comment]
是这样的，为了提高项目的稳定性，从这次 v1.1.0 无限极目录开始，新功能出来后不会再立即发布了，而是先在小范围内放出预览版，然后至少一周以后再在各大平台上发布正式版  
如果想要最新功能的版本，在分支 preview 中直接下载 zip 就可以了，否则就要晚一周

**Comment by TevinLi** [comment]
另外，趁此机会解释一下目前我创建的另外两个分支 😺   
![wechatimg2](https://cloud.githubusercontent.com/assets/11657489/26094106/256cb338-3a4b-11e7-8cf6-86726f86c672.png)
develop 开发好一个新功能就合并到 preview ，然后 preview 放出一个预览版，而如果预览版有 bug 就直接在 preview 上进行修复，然后合并到 master 发布正式版。  
这样的好处是：  
- develop 和 preview 可以并行开发
- master 只负责发布，能保持更好的稳定性，不再怕别人 fork 的代码还带着 bug，或者一进来 github 就直接下载还在调试的 zip

**Comment by choicky** [comment]
git 的正确姿势就是那样的 😀

**Comment by TevinLi** [comment]
无限级目录支持，已于 [v1.1.0](https://github.com/TevinLi/amWiki/releases/tag/v1.1.0) 实现
