### ISSUE TITLE
有序列表后面跟无序列表，预览会自动变成有序列表

### ISSUE THREAD

**Issue by jacksoncode** [TevinLi/amWiki#54]
有序列表后面跟无序列表，预览时，后面的无序列表会自动变成有序列表
举个例子：

1. text
- 无序1
- 无序2

在httpserver里打开就变成：
1. text
2. 无序1
3. 无序2 

在其他的markdown编辑器中预览时正常的。
VSCode/haroopad等没问题，但markdownpad好像也有这个问题。

**Comment by TevinLi** [comment]
从逻辑上说，有序列表后面平级且紧跟无序列表的情况还是非常少见的，在这种特例的情况下，建议通过敲两个回车来断开两个列表间的关联  
(MarkdownPad 好像不理会有几个换行，但是 amWiki 中两换行是有效的)
