### ISSUE TITLE
amWiki采用html预览插件，乱码如何解决？

### ISSUE THREAD

**Issue by hongyuXie** [TevinLi/amWiki#61]
如题：atom安装了amWiki插件后，编写文档方便多了，但是，为了预览方便，安装了atom-html-preview插件https://github.com/webBoxio/atom-html-preview
，但是预览效果却是乱码
如下图：

![1](https://user-images.githubusercontent.com/29282760/27008927-b541b294-4eb2-11e7-96b1-4c083d5d4c86.png)

**Comment by TevinLi** [comment]
这是姿势不对哈  
首先，这是 Markdown 文档，直接预览要用 Atom 自带的 markdown-preview ，快捷键 Ctrl+M  
其次，amWiki 在 Atom 中可以直接快捷键 F12 启动本地服务器呼起浏览器来看实际效果

**Comment by hongyuXie** [comment]
我已经知道了
markdown-preview 这个知道，我以为还能DW一样，直接所见即所得查看Markdown 文档的web效果。
发现不行，不能那么用，还有想不乱码，也可以在 Markdown 文档上加上 ：<meta charset="utf-8">也能看，不过没必要了
不过要是amWiki的Markdown 文档可以支持直接 markdown-preview 还有内部浏览器直接看，应该是个很不错的亮点。不知道大大有没有考虑过呢？

**Comment by TevinLi** [comment]
除了图片因为路径问题 markdown-preview 会看不到，其他 markdown-preview 能预览呀  
不过不会支持将整个 amWiki 项目在 Atom 中打开，定位上来说 amWiki 主要着重的是 wiki 而不是笔记，太强调所见即所得就偏向笔记去了，何况配置不高的机器有可能会卡得不能动了

**Comment by hongyuXie** [comment]
恩，楼主大大的说法，接受并认可，the question has fixed! please  closed 
目前来说，基本上markdown-preview能看到效果了，因为我最开始写的是导图，刚开始用上amWiki，操作不熟悉，图片路径也是试了好几次，每次还都得切换到浏览器去看，来来回回试了好多次，所以才有此一问。
