### ISSUE TITLE
关于超长文档页内目录示例--此处的业内目录只能一个个手敲么？

### ISSUE THREAD

**Issue by hongyuXie** [TevinLi/amWiki#62]
如题：超长文档页内目录,该目录只能用手一个个敲么，有没有直接拖拽方式？
比如，在nodepad++/doc等工具里面已经编写好的目录的文档直接拖过来能识别么？有没有支持的方式? 

 #另：关于在issues中上传图片或者文件，经常失败，大大知道什么原因么？我在 #61 中还能上传，不过也是试了好久才传上来的

**Comment by TevinLi** [comment]
文档页内目录，有两种方式：  

1.  通过 Atom 菜单`提取h2、h3标题为页内目录`生成
      优点：目录都在文档里是链接+列表的形式，可以很好的和其他平台兼容  
      缺点：每次标题改动都要重新生成
2. 通过标记 `[TOC]` 或 `[MENU]` 指定目录生成位置，在页面上渲染的时候，会解析成目录
      优点：文档标题结构改动，无需重新生成
      缺点：一些其他平台不支持这个标记

amWiki 还有一种页内目录，在页面左下角有个悬浮窗，每次切换文档的时候，都会渲染成当前文档的页内目录，类似在这里加了一个[TOC]，而且由于是悬浮窗，只会收缩不会消失，某些场景下比在文档上设置页内目录还好用  
所以如果不考虑其他 Markdown 平台只在 amWiki 上使用，在文档上有没有页内目录，其实关系不大

**Comment by TevinLi** [comment]
现在上传图片确实经常失败，我也是很多次尝试偶尔才能成功  
（有时候，去一个从来没人发 issue 的地方发起一个新的 issue，这个时候上传图片成功率高很多，至于为啥我也不知道 :smile_cat: ）

**Comment by hongyuXie** [comment]
文档页内目录：
第一个方式：好像无意中见过，我再试试
第二个方式：完全是还没开始玩，我搞一下

现在是在Atom里面基于amWiki写文档，之后会上传到gitHub上，这样也不会影响目录结构(页内或者左侧树目录)吧？

最近在写文档，关于左侧树目录，一会新开一个issue给楼主大大提两个建议。
