### ISSUE TITLE
标题中有空格点击目录无法跳转，怎么解决？

### ISSUE THREAD

**Issue by joy117** [TevinLi/amWiki#64]
非常感谢amWiki～
生成目录很好用，就是有一点问题，如果全中文，点击目录就可以页内跳转至相应章节。
但是如果h2或h3标题有中文也有英文，例如“中文 English 混合”，或者有2个及以上英文单词，如“pull request”，这种标题生成的目录，点击目录，无法跳转至相应章节。
有什么办法解决吗？
谢谢～

**Comment by TevinLi** [comment]
收到问题
这个问题其实还是很简单的，只要对生成目录的链接地址部分进行移除空格处理，描点生成的时候同样移除空格即可，后面的版本我就加上

**Comment by joy117** [comment]
谢谢回答～
2个以上英文单词，所有字母小写，把空格变成-，可以跳转了。
但是特殊字符还是不行，比如“pull & push”，这种字符该怎么处理呢？

**Comment by TevinLi** [comment]
自动生成等后面我加上这个问题的容错处理吧  

你现在的问题的话，可以 `[中文 pull & push](#中文%20pull%20%26%20push "中文 pull & push")` 这样临时处理

**Comment by joy117** [comment]
好的，谢谢～
期待后续版本～

**Comment by TevinLi** [comment]
经过分析：  
1. 未发现空格造成无法访问的问题
2. 发现带`&`符的文件，能从导航点开，却不能从url打开也不能刷新
    这是因为`&`是url的参数分割标示符，所以冲突了，下一版本中，在导航跳转的时候，将对这个字符单独转义，从而支持新开和刷新
