### ISSUE TITLE
关于amWiki通过iframe引入线上视频链接以后，后面的文字显示不出来，请大大确认是否是bug

### ISSUE THREAD

**Issue by hongyuXie** [TevinLi/amWiki#65]
如题，在atom基于amWiki写了一篇markdown文档，文档中通过iframe引入了一个在线视频链接，后面会有文字等，但是通过在浏览器中打开当前文档，只看到视频看不到视频后面的内容了，同样的内容，我在CSDN上试验了一次，可以正常显示，CSDN链接如下：
http://blog.csdn.net/loverain90/article/details/73287420
而在amwWiki本地打开的效果如下：
![1](https://user-images.githubusercontent.com/29282760/27168993-9bba5800-51da-11e7-9bd1-41f08ab728f3.png)

如下是基于amwiki编写的文档内容：
----------start----------【
# 非监督学习
## 视频
<iframe height=510 width=900 src="https://d3c33hcgiwev3.cloudfront.net/01.4-V2-Introduction-UnsupervisedLearning-FairUse.8f251df0b23611e4af4203f82f647410/full/540p/index.webm?Expires=1497657600&Signature=cgy7sBQkMxLRrHbRq-gVs4VZ5Sjr3URFsglQHmqH0nsYruHsyN6ftC~NxaxZxdfbsZgjPYoHBHSWi-rtl-Sk3yiMshR6AvQTsSZEk60I9jrF9lC4RXIfRBj4bWPiB46I9mSFqQZ2PCs4cb5b0889SIiQpPqG8Xf7wei7volq2q0_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A">  
## English
0:00
In this video, we'll talk about the second major type of machine learning problem, called Unsupervised Learning.

】--------end---------

**Comment by TevinLi** [comment]
插入 html 需要较为严格的遵守代码规范，iframe 的标准格式如下
`<iframe height=510 width=900 src="..."></iframe>`
你的问题，补齐 **</iframe>** 即可

**Comment by hongyuXie** [comment]
this problem has fixed,还是我不规范引起的。thx 大大。please closed it。
这是因为amWiki做了检查么？同样的代码在CSDN竟然没问题。

**Comment by TevinLi** [comment]
没，其实不是检查了，恰恰相反，CSDN应该是做改进了，认为这个不完整即不影响安全又不影响表意问题，然后就做了自动修复  
不过 amWiki 可能短时间内不会做这个，毕竟精力有限呀，还是养成良好的标准习惯为好 :smile:
