### ISSUE TITLE
大大，求tutorial:基于atom和amwiki写的md文档如何整合到github wiki上？

### ISSUE THREAD

**Issue by hongyuXie** [TevinLi/amWiki#66]
如题：
现在我想把基于atom和amwiki编写的个人wiki放到github wiki上，并且保持在本地web上浏览的效果一样，如何操作？在win7系统上，已经neng导出当前文库为github wiki了，现在也能上传到github上，只不过不知怎么做才能保持和本地web上看到的效果一样？
如下链接：https://github.com/hongyuXie/xhy.github.io 这是我在atom中导出为github wiki后，然后通过github desktop上传的。
参考了issue #20 和 #32 自己尝试了几次，还是没搞清楚，囧。
github新手+amwiki新手，所以还得请大大，给点支持。或者有没有教程链接
并且希望整合到github上的wiki和本地web查看效果一致：
![1](https://user-images.githubusercontent.com/29282760/27272960-78eeeb42-54ff-11e7-92dc-17d96b796782.png)

**Comment by Newbe36524** [comment]
![tim 20170619145833](https://user-images.githubusercontent.com/7685462/27273052-d9671332-54ff-11e7-8d78-c7ac8df0bf6a.png)

**Comment by TevinLi** [comment]
你的链接是 github page 不是 github wiki  

page 的话，只需要直接把创建的文档传上去即可，amWiki web 端设计标准就是在 github page 上可以使用  

wiki 的话，先把 `clone this wiki locally` 的 git 地址克隆到本地，然后导出的时候选择这个文件夹，然后再上传即可

**Comment by hongyuXie** [comment]
![2](https://user-images.githubusercontent.com/29282760/27273496-deea8c6a-5501-11e7-91a0-b869c78557ae.png)
@TevinLi 大大，我这姿势是不是有问题？？

**Comment by TevinLi** [comment]
直接用 git clone 试试，不用 github 客户端

**Comment by TevinLi** [comment]
github page 才能和本地显示一样，github wiki 只能显示和本地相同的内容

**Comment by hongyuXie** [comment]
![3](https://user-images.githubusercontent.com/29282760/27273835-4fef78ac-5503-11e7-92c1-dd33d40cc795.png)
![4](https://user-images.githubusercontent.com/29282760/27274070-695ac520-5504-11e7-8d2d-9598170ea5e1.png)

**Comment by TevinLi** [comment]
用你自己的库附带的 wiki  

![image](https://user-images.githubusercontent.com/11657489/27274204-0363a4fc-5505-11e7-9545-7dbb47085cf6.png)

`https://github.com/TevinLi/amWiki.wiki.git` 是我这边的，推送到我这边，应该是需要权限的

**Comment by hongyuXie** [comment]
大大，还得再请求支援，我现在上传上去了，但是通过amwiki的导航直接404了，找不到页面啊
https://github.com/hongyuXie/xhy.github.io/wiki

**Comment by TevinLi** [comment]
config.json 的 github-url 不对，这个是主项目的地址，而不是 wiki 的地址  
你的这里应该是`https://github.com/hongyuXie/xhy.github.io`

**Comment by hongyuXie** [comment]
谢谢大大支持。github wiki的方式可以了，https://github.com/hongyuXie/xhy.github.io/wiki
一会再弄弄github pages的方式

**Comment by hongyuXie** [comment]
`page 的话，只需要直接把创建的文库传上去即可，amWiki web 端设计标准就是在 github page 上可以使用`
大大这话的意思是不是，直接上传整个atom构建的那个目录就行？

**Comment by YaoXuanZhi** [comment]
嗯嗯，大体就是这样的，不过要注意，那个docs其实就是amWiki文库的根目录，不要搞错层级关系哦

**Comment by hongyuXie** [comment]
@YaoXuanZhi @TevinLi  感谢感谢，已经整好

但是发现视频链接貌似有时间限制，有些视频链接可以，有些提示访问拒绝
比如：下面这个可以
https://hongyuxie.github.io/?file=001-%E5%AD%A6%E4%B9%A0MachineLearning/01-Week1/5-Linear%20Algebra%20Review/6-Inverse%20and%20Transpose/1-video
而下面这个不可以
https://hongyuxie.github.io/?file=001-%E5%AD%A6%E4%B9%A0MachineLearning/01-Week1/3-Mode%20and%20Cost%20Function/1-Model%20Representation/1-video
两位大大有何高见？这中视频我是通过浏览器中F12直接查看链接，将链接copy下来，在md文档中通过iframe引入

举例：网页上有一个视频页面，我不想下载该视频，而且下载视频的话，好像不能通过像图片那样加入到md文档中，并且文档会很大……
举例网页：https://www.coursera.org/learn/machine-learning/lecture/RKFpn/welcome

**Comment by YaoXuanZhi** [comment]
我觉得可能是视频URL不对，或者链接太长了，导致出现了此问题，建议在本地看看能否正常访问，或者找一些工具验证视频地址是否有（以上只是猜测，这方面我也没有什么研究呢，所以帮不上什么忙啦〒_〒）

**Comment by hongyuXie** [comment]
@YaoXuanZhi  谢谢建议，我现在发现我那个wik确实可读性不行，之前都是在CSDN用markdown上写，发出来页面方式看起来不错就不管了
不过同样的东西 git pages方式还不错，git wiki 太囧了……
GitBook 暂时还没有了解到，刚才看了一下，发现和amWiki是一样的吧？

**Comment by hongyuXie** [comment]
@YaoXuanZhi  关于视频url链接失效，原因我应该是找到了，我是直接从静态页面通过F12拿到的链接，这应该是混淆过的，所以过一段时间就失效了。
我试着参考着这个看看：http://www.jianshu.com/p/c10c3f254710

实在不行，就直接把视频down下来，放到amwiki工程目录下，像图片一样引用，再看行不行了

**Comment by hongyuXie** [comment]
@YaoXuanZhi  大大，我在 #32 中看到你有一张gif图，看到你也是win下用tortoiseGit来管理同步代码提交，有没有发现push/pull等操作时候，很慢，甚至会失败?参考了一下，https://stackoverflow.com/questions/10790232/hanging-at-post-git-receive-pack-chunked
说是配置git config http.postBuffer 524288000，但是我右键tortoiseGit还是不知道在哪配置？或者只是直接在git bash输入命令：git config http.postBuffer 524288000 就行？这样在git bash输入是永久有效的还是临时的，还有这样在git bash命令窗口输入的配置，同时也会在tortoiseGit生效么？
如下图是在tortoiseGit下将本地的更新push到远程，失败了：
![1](https://user-images.githubusercontent.com/29282760/27364353-b5c3b30e-566c-11e7-84ce-94a9a5fa1f7a.png)
如下图是在git bash下将本地的更新push到远程，很慢，暂时不知道是否能成功：
![2](https://user-images.githubusercontent.com/29282760/27364389-f6b7db10-566c-11e7-862f-839713940703.png)

**Comment by hongyuXie** [comment]
@YaoXuanZhi  用git bash命令提交的方式，进过测试，是可以成功提交到远程仓库的，但是速度慢到不行，囧！！而用tortoiseGit提交试了2次都是失败报错如下图
![3](https://user-images.githubusercontent.com/29282760/27365299-f3979cb8-5671-11e7-8801-0a27d89b33a7.png)

并且我这里还是开了VPN的情况下，还是慢

![4](https://user-images.githubusercontent.com/29282760/27365332-21924dd4-5672-11e7-918c-81c8155fd543.png)

**Comment by mikusjelly** [comment]
视频的话，不建议直接往github上面放，最好传其他视频网站。
github提交代码，我是直连完全没有问题的。

另外，这个issue可以关了。
