### ISSUE TITLE
有什么办法能够实现对整个文库进行全文搜索？

### ISSUE THREAD

**Issue by hamdichau** [TevinLi/amWiki#7]
1. 感谢博主优秀作品！真的很棒！  
2. 若是单篇文档全文检索，自然不是问题。想请教博主，若是对整个文库进行关键词检索，其实现途径有哪些？

**Comment by TevinLi** [comment]
在浏览器端对文库进行缓存，localStorage与indexedDB这种，其实目前这问题也有考虑，想过几种方案：  

- 仅localStorage存储，因为不支持localStorage的浏览器已经不提供访问支持，所以只要能打开就能使用搜索
- 仅indexDB存储，支持的浏览器才开放搜索功能，这个以现在的市场份额来看，估计要挂蛮多浏览器了
- 两者混合，indexDB优先，但是开发成本较大

然后在这两种情况更新缓存：一个是打开那一篇文档的时候更新那一篇的，一个点击全局更新功能按钮

**Comment by TevinLi** [comment]
已经在 [v0.7.0](https://github.com/TevinLi/amWiki/releases/tag/v0.7.0) 中实现全库搜索，由于时间关系目前使用的是 localStorage，后面会再考虑安排时间做成indexDB优先
