### ISSUE TITLE
不支持转义

### ISSUE THREAD

**Issue by mikusjelly** [TevinLi/amWiki#71]
Hi @TevinLi ,

那些不想被Markdown解析的字符，一般是用`\`转义，就不会被解析了。
但是amWiki好像不支持。

举个例子，一个表格：
```
|test|test|
|--|--|
|a\|b|a or b|  
```

默认效果：

|test|test|
|--|--|
|a\|b|a or b|

但是amWiki会无视`\`，继续解析。

**Comment by TevinLi** [comment]
收到

**Comment by mikusjelly** [comment]
另外一个也是。

```
|test|test|
|--|--|
|[^abc]+|a or b|  
```
希望的效果是：

|test|test|
|--|--|
|[^abc]+|a or b|  

这个amWiki会翻译成：

[1]+ 脚注。

**Comment by TevinLi** [comment]
好的，收到   

这都是 [marked.js](https://github.com/chjj/marked) 的坑 :joy:，这个项目的作者估计已经停止新功能开发了，偶尔维护一两个非常严重的 bug，很多正则和渲染都是我自己写的，我有时候都想单独开炉了

**Comment by TevinLi** [comment]
额，这样写的脚注不是应该解释为脚注的么？你是说加过处理的脚注，例如 `\[^abc]` 还是被解释了，是的不？

**Comment by mikusjelly** [comment]
嗯，`[\^abc]`写法会不会更易于理解一些？表示不对`^`进行解析。
而`\|`表示不对`|`进行解析，语法上一致，会不会比较好？

**Comment by TevinLi** [comment]
嗯嗯，这是同一个问题，到时候会一起修复

**Comment by mikusjelly** [comment]
发现 [增加"\\"符转义功能](https://github.com/TevinLi/amWiki/commit/0b933ba6a6d29d48f50872b4a0ef513ec4ee9b20)
