### ISSUE TITLE
支持 Mermaid

### ISSUE THREAD

**Issue by mikusjelly** [TevinLi/amWiki#72]
[Mermaid](https://knsv.github.io/mermaid/#mermaid)  支持以下三种：
- Flowcharts 
- Sequence diagrams
- Gant diagrams

文档：https://mermaidjs.github.io/

**Comment by TevinLi** [comment]
嗯嗯，可以的

**Comment by mikusjelly** [comment]
最近用mermaid比较多，感觉这个太强大了；功能直接覆盖了流程图、时序图。

**Comment by TevinLi** [comment]
嗯嗯，确实很不错 :ok_hand:

**Comment by 672399809** [comment]
搜索issues过来的，来顶一把mermaid，作者加油，感谢

**Comment by mikusjelly** [comment]
![2018-02-27_161315](https://user-images.githubusercontent.com/2801072/36717483-329b3bc2-1bd9-11e8-9ff3-681553b84992.png)

最近因为要用这个东西，自己弄好了，例子看图。

**Comment by mikusjelly** [comment]
mermaid 的用法请参考文档 https://mermaidjs.github.io/。
Atom有对应的mermaid插件，我个人使用Typro写文档。

**Comment by 672399809** [comment]
@mikusjelly 太棒了

**Comment by doloers** [comment]
很奇怪，按照mermaid的文档操作了，但还是没办法使用
