### ISSUE TITLE
序号问题

### ISSUE THREAD

**Issue by mikusjelly** [TevinLi/amWiki#73]
MD的目录结构这么写的，
```
2. 基础
2.1 数据类型
2.2 方法说明
```

展示出来是：

![2017-07-13_164844](https://user-images.githubusercontent.com/2801072/28158100-2eebec62-67eb-11e7-9415-51f47ba9ea8f.png)

不是很美观，序号能否由作者自定义，而不是自动生成？
毕竟每个人写作习惯都不一样，有的人可能还需要用到一、二、三等各种中文序号。

**Comment by TevinLi** [comment]
重复的问题 at #33  

对了，我添加了一份[开发计划表](https://github.com/TevinLi/amWiki/blob/master/SCHEDULE.md)，此问题计划是在 v1.2.1 中修复

**Comment by mikusjelly** [comment]
看到了。
