### ISSUE TITLE
关于数学公式

### ISSUE THREAD

**Issue by mikusjelly** [TevinLi/amWiki#74]
这个看起来不错  [MathJax](https://github.com/mathjax/MathJax)：

例子1：
```
$$
\mathbf{V}_1 \times \mathbf{V}_2 =  \begin{vmatrix} 
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial X}{\partial u} &  \frac{\partial Y}{\partial u} & 0 \\
\frac{\partial X}{\partial v} &  \frac{\partial Y}{\partial v} & 0 \\
\end{vmatrix}
$$
```
效果：
![2017-07-13_183921](https://user-images.githubusercontent.com/2801072/28162699-9a66e76c-67fa-11e7-9964-51b3a24a188c.png)

例子2：
```
$\lim_{x \to \infty} \exp(-x) = 0$
```
效果
![image](https://user-images.githubusercontent.com/2801072/28162723-af1c86d0-67fa-11e7-80bf-e56e1b9eae6b.png)

**Comment by TevinLi** [comment]
Nice，就这个

**Comment by TevinLi** [comment]
MathJax这个项目有点狠啊，一百多个零散文件，没有单文件模式…  
虽然不是每次都用这么多文件，但是也不确定每次具体会要用到哪几个文件...  

不知道有没有其他好点的处理方式，如果没有的话，就暂时走 cdn 的方式吧，cdn.mathjax.org 这个虽然在美国，但应该在天巢 great wall 白名单里，国内也有 bootcss.com 的 cdn  
唯一的麻烦是，断网了就显示不了数学公式了  
等插件模式出来后，如果需要，再封装一个数学公式的离线插件吧，主项目就不携带这一百多个文件了

**Comment by mikusjelly** [comment]
同意优先cdn。

[MathJax CDN shutting down on April 30, 2017.](https://www.mathjax.org/cdn-shutting-down/) 
官方的 cdn.mathjax.org 已经关闭了，用国内的cdn http://www.bootcdn.cn/mathjax/ 即可。

断网什么，不存在。

至于离线模式的插件，后续再考虑吧。
（功能出来就可以装逼了，那些搞机器学习的，其实有挺多的数学公式的…… :-)）

**Comment by TevinLi** [comment]
嗯嗯，好的，感觉玩机器学习的都是大神啊，哈哈

**Comment by mikusjelly** [comment]
看到其他issue有人建议用Katex，我个人习惯用Typro写文档，它内部支持的就是Mathjax，还是用这个好了。
