### ISSUE TITLE
/usr/bin/env: "node\r": 没有那个文件或目录

### ISSUE THREAD

**Issue by louisliaoxh1989** [TevinLi/amWiki#77]
Mac：
/usr/bin/env: "node\r": 没有那个文件或目录  

Linux：
![image](https://user-images.githubusercontent.com/11657489/28905951-95d23448-7846-11e7-9f23-e067a8503cf5.png)

**Comment by TevinLi** [comment]
奇怪了，我以为是我没有转换的原因，然而并不是  
检查了一下我本地的开发环境，全都是 Unix 换行符，下载了 github 的 zip，也都是 Unix 换行符，唯独从 npm install 下来的代码，却都变成 Windows 换行符了  
之前 npm 发布并不会这样，肯定是和本地一样的，嗯...下个版本发布我在另外一个系统上试试

**Comment by TevinLi** [comment]
手工修正的方法很简单：  
对文件 /usr/local/node***/lib/node_modules/amwiki/bin/main.js  

方法一：编辑器打开，正则替换  `\r\n` 为 `\n` 即可  

方法二：从 https://raw.githubusercontent.com/TevinLi/amWiki/master/bin/main.js 下载同一文件，然后覆盖此文件即可
