### ISSUE TITLE
第二级目录不能使用粘贴图片功能，第一季目录下可以。

### ISSUE THREAD

**Issue by pianzide1117** [TevinLi/amWiki#8]
![image](https://cloud.githubusercontent.com/assets/7685462/17898098/1c2e0fc6-6989-11e6-8e1f-78da5d77e51a.png)
第二级目录不能使用粘贴图片功能，第一季目录下可以。

**Comment by TevinLi** [comment]
收到，肯定是路径问题

**Comment by TevinLi** [comment]
已在 [v0.6.2](https://github.com/TevinLi/amWiki/releases/tag/v0.6.2) 版本中修复此问题
