### ISSUE TITLE
如何更新安装好的版本？

### ISSUE THREAD

**Issue by MXWXZ** [TevinLi/amWiki#83]
我已经使用amwiki创建了一个文档，然后如果有版本更新应该复制那些文件或者在哪里可以找到更新的按钮？

**Comment by TevinLi** [comment]
amWiki 分工作端和Web端，同样的升级也分两部分升级  
工作端升级，重新安装新版本即可  
Web端升级，在工作端升级完成后在文库目录重新创建即可，这个二次创建操作主要覆盖 ./amWiki 文件夹下的内容，不会修改 ./library ./assets 等文件夹下的任何文件

**Comment by MXWXZ** [comment]
也就是说我工作端安完新版本后重点一次从Config.json创建就好了？

**Comment by TevinLi** [comment]
是的，如果你没有自己对程序进行修改的话，重新创建即可 :smiley_cat:
