### ISSUE TITLE
测试接口的功能应该加入Delete和Put方法的支持

### ISSUE THREAD

**Issue by pianzide1117** [TevinLi/amWiki#9]
Delete和Put作为Restful接口的重要方法，也应该需要被支持。

**Comment by TevinLi** [comment]
已收到

**Comment by TevinLi** [comment]
Restful API 是一种优秀的接口设计风格，应该支持！
已经在 [0.6..3](https://github.com/TevinLi/amWiki/releases/tag/v0.6.3) 版本实现，感谢你的建议

**Comment by TevinLi** [comment]
因为墙的原因，v0.6.3 推送到 atom 的 apm 失败，又因为 apm 发布的一些奇怪约定，可能只能从 github 下载手工升级了，或者等下个版本推送

**Comment by pianzide1117** [comment]
good job
